variables:
  DOCKER_IMAGE: "ghcr.io/astral-sh/uv:python3.12-bookworm-slim"
  UV_CACHE_DIR: ".uv-cache"

stages:
  - test

test-job:
  stage: test
  image: $DOCKER_IMAGE

  cache:
    key: deps-cache
    paths:
      - .uv-cache
      - /usr/bin/ffmpeg

  before_script:
    - apt-get update && apt-get install -y ffmpeg
    - uv sync --extra dev --frozen

  script:
    - uv run playwright install --with-deps chromium
    - uv run audiobook-tool -h
    - uv run pytest

  only:
    - main
