services:
  cli:
    build: .
    # image: audiobook-cli
    container_name: audiobook_tool
    stdin_open: true
    tty: true
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    environment:
      - PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
