[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "audiobook-cli"
version = "0.3.1"
description = "Ultimate Python CLI to handle audiobooks."
readme = "README.md"
authors = [{ name = "Ewilan Rivière" }]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "Environment :: Console",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.12",
]

# deptry .
# uv sync
# uv export --format requirements-txt > requirements.txt
dependencies = [
  # https://pypi.org/project/importlib-metadata/
  "importlib-metadata", # import importlib_metadata (for version)
  # https://pypi.org/project/PyYAML/
  "pyyaml", # import yaml (to handle .yml files)
  # https://pypi.org/project/mutagen/
  "mutagen", # import mutagen (to handle .mp3 and .m4b files)
  # https://pypi.org/project/python-dotenv/
  "python-dotenv", # import dotenv (to handle .env variables)
  # https://pypi.org/project/httpx/
  "httpx", # import httpx (to download audiobook cover)
  # https://pypi.org/project/rich/
  "rich", # import rich (help for debugging)
  # uv run playwright install chromium
  # https://pypi.org/project/playwright/
  "playwright", # import playwright (for Audible web scraping)
  # https://pypi.org/project/playwright-stealth/
  "playwright-stealth", # import playwright_stealth
  "pytest>=8.0.2",
]

[project.scripts]
audiobook-tool = "audiobook.app:main"

[project.optional-dependencies]
dev = ["pytest~=8.0.0", "pytest-cov", "uv>=0.5.0"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.deptry]
known_first_party = ["audiobook"]

[tool.deptry.per_rule_ignores]
DEP002 = ["pytest", "pytest-cov", "uv"]

[tool.deptry.package_module_name_map]
uv = "uv"

[dependency-groups]
dev = ["pytest-cov>=7.0.0"]
