[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "audiobook-cli"
version = "0.1.0"
description = "Ultimate Python CLI to handle audiobooks."
readme = "README.md"
authors = [{ name = "Ewilan Rivière" }]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "Environment :: Console",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.12",
]

# deptry .
# uv sync
# uv export --format requirements-txt > requirements.txt
dependencies = [
  "pyyaml",        # import yaml (to handle .yml files)
  "mutagen",       # import mutagen (to handle .mp3 and .m4b files)
  "python-dotenv", # import dotenv (to handle .env variables)
  "urllib3",       # import urllib3 (to download audiobook cover)
  "rich",          # import rich (help for debugging)
  # uv run playwright install chromium
  "playwright",         # import playwright (for Audible web scraping)
  "playwright-stealth", # import playwright_stealth
  "pytest>=8.0.2",
]

[project.scripts]
audiobook-tool = "audiobook.app:main"

[project.optional-dependencies]
dev = ["pytest~=8.0.0", "uv>=0.5.0"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.deptry]
known_first_party = ["audiobook"]

[tool.deptry.per_rule_ignores]
DEP002 = ["pytest", "pytest-cov", "uv"]

[tool.deptry.package_module_name_map]
uv = "uv"
