name: Test Audiobook Tool

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*"

env:
  UV_CACHE_DIR: /tmp/.uv-cache
  PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/.cache/ms-playwright

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Force install Node
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-path: "uv.lock"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ffmpeg

      - name: Cache Playwright Browsers
        # if: "startsWith(github.ref, 'refs/tags/')"
        uses: actions/cache@v4
        with:
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}
          key: ${{ runner.os }}-playwright-${{ hashFiles('uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install dependencies
        run: uv sync --frozen --extra dev

      - name: Install Playwright Chromium
        # if: "startsWith(github.ref, 'refs/tags/')"
        run: |
          uv run playwright install-deps chromium
          uv run playwright install chromium

      - name: Run Tool Check
        run: uv run audiobook-tool -h

      # - name: Execute tests (Standard)
      #   if: "!startsWith(github.ref, 'refs/tags/')"
      #   run: uv run pytest -k "not audible"

      # - name: Execute tests with coverage (Only Tags)
      #   if: "startsWith(github.ref, 'refs/tags/')"
      #   run: uv run pytest --cov --cov-branch --cov-report=xml

      - name: Execute tests
        # run: uv run pytest --cov --cov-branch --cov-report=xml
        run: uv run pytest -k "not audible" --cov --cov-branch --cov-report=xml

      - name: Send code coverage (Only Tags)
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: false
